"""add otp_purpose field in user table

Revision ID: 1198cb3e4871
Revises: 99ddc479a5b4
Create Date: 2026-08-19 16:41:07.156644

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "1198cb3e4871"
down_revision: Union[str, Sequence[str], None] = "99ddc479a5b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("otp_purpose", sa.Text(), nullable=True), schema="deskconn")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "otp_purpose", schema="deskconn")
    # ### end Alembic commands ###
