"""access management

Revision ID: 99ddc479a5b4
Revises: ee815c8ca96f
Create Date: 2026-05-13 14:15:14.909650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "99ddc479a5b4"
down_revision: Union[str, Sequence[str], None] = "ee815c8ca96f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


desktop_access_role = postgresql.ENUM(
    "owner", "admin", "member", name="desktop_access_role", schema="deskconn", create_type=False
)
invitation_status = postgresql.ENUM(
    "pending", "accepted", "rejected", "expired", name="invitation_status", schema="deskconn", create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "desktop_invites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("role", desktop_access_role, nullable=False),
        sa.Column("status", invitation_status, nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("desktop_id", sa.UUID(), nullable=False),
        sa.Column("inviter_id", sa.UUID(), nullable=False),
        sa.Column("invitee_user_id", sa.UUID(), nullable=True),
        sa.Column("invitee_organization_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["desktop_id"], ["deskconn.desktops.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["invitee_organization_id"], ["deskconn.organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["invitee_user_id"], ["deskconn.users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["inviter_id"], ["deskconn.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="deskconn",
    )
    op.create_index(
        op.f("ix_deskconn_desktop_invites_desktop_id"),
        "desktop_invites",
        ["desktop_id"],
        unique=False,
        schema="deskconn",
    )
    op.create_index(
        op.f("ix_deskconn_desktop_invites_invitee_organization_id"),
        "desktop_invites",
        ["invitee_organization_id"],
        unique=False,
        schema="deskconn",
    )
    op.create_index(
        op.f("ix_deskconn_desktop_invites_invitee_user_id"),
        "desktop_invites",
        ["invitee_user_id"],
        unique=False,
        schema="deskconn",
    )
    op.create_index(
        op.f("ix_deskconn_desktop_invites_inviter_id"),
        "desktop_invites",
        ["inviter_id"],
        unique=False,
        schema="deskconn",
    )
    op.create_table(
        "desktop_organization_access",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("role", desktop_access_role, nullable=False),
        sa.Column("desktop_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["desktop_id"], ["deskconn.desktops.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["deskconn.organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("desktop_id", "organization_id", name="uq_desktop_organization_access"),
        schema="deskconn",
    )
    op.create_index(
        op.f("ix_deskconn_desktop_organization_access_desktop_id"),
        "desktop_organization_access",
        ["desktop_id"],
        unique=False,
        schema="deskconn",
    )
    op.create_index(
        op.f("ix_deskconn_desktop_organization_access_organization_id"),
        "desktop_organization_access",
        ["organization_id"],
        unique=False,
        schema="deskconn",
    )
    op.create_table(
        "desktop_user_access",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("role", desktop_access_role, nullable=False),
        sa.Column("desktop_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["desktop_id"], ["deskconn.desktops.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["deskconn.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("desktop_id", "user_id", name="uq_desktop_user_access"),
        schema="deskconn",
    )
    op.create_index(
        op.f("ix_deskconn_desktop_user_access_desktop_id"),
        "desktop_user_access",
        ["desktop_id"],
        unique=False,
        schema="deskconn",
    )
    op.create_index(
        op.f("ix_deskconn_desktop_user_access_user_id"),
        "desktop_user_access",
        ["user_id"],
        unique=False,
        schema="deskconn",
    )
    op.drop_index(op.f("ix_deskconn_desktop_access_desktop_id"), table_name="desktop_access", schema="deskconn")
    op.drop_index(op.f("ix_deskconn_desktop_access_member_id"), table_name="desktop_access", schema="deskconn")
    op.drop_table("desktop_access", schema="deskconn")
    op.drop_index(op.f("ix_deskconn_desktops_organization_id"), table_name="desktops", schema="deskconn")
    op.drop_constraint(op.f("uq_desktop_org_name"), "desktops", schema="deskconn", type_="unique")
    op.create_unique_constraint("uq_desktop_user_name", "desktops", ["user_id", "name"], schema="deskconn")
    op.drop_constraint(op.f("desktops_organization_id_fkey"), "desktops", schema="deskconn", type_="foreignkey")
    op.drop_column("desktops", "organization_id", schema="deskconn")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "desktops", sa.Column("organization_id", sa.UUID(), autoincrement=False, nullable=False), schema="deskconn"
    )
    op.create_foreign_key(
        op.f("desktops_organization_id_fkey"),
        "desktops",
        "organizations",
        ["organization_id"],
        ["id"],
        source_schema="deskconn",
        referent_schema="deskconn",
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_desktop_user_name", "desktops", schema="deskconn", type_="unique")
    op.create_unique_constraint(
        op.f("uq_desktop_org_name"),
        "desktops",
        ["organization_id", "name"],
        schema="deskconn",
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_deskconn_desktops_organization_id"), "desktops", ["organization_id"], unique=False, schema="deskconn"
    )
    op.create_table(
        "desktop_access",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("role", desktop_access_role, autoincrement=False, nullable=False),
        sa.Column("member_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("desktop_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["desktop_id"], ["deskconn.desktops.id"], name=op.f("desktop_access_desktop_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["deskconn.organization_members.id"],
            name=op.f("desktop_access_member_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("desktop_access_pkey")),
        schema="deskconn",
    )
    op.create_index(
        op.f("ix_deskconn_desktop_access_member_id"), "desktop_access", ["member_id"], unique=False, schema="deskconn"
    )
    op.create_index(
        op.f("ix_deskconn_desktop_access_desktop_id"), "desktop_access", ["desktop_id"], unique=False, schema="deskconn"
    )
    op.drop_index(op.f("ix_deskconn_desktop_user_access_user_id"), table_name="desktop_user_access", schema="deskconn")
    op.drop_index(
        op.f("ix_deskconn_desktop_user_access_desktop_id"), table_name="desktop_user_access", schema="deskconn"
    )
    op.drop_table("desktop_user_access", schema="deskconn")
    op.drop_index(
        op.f("ix_deskconn_desktop_organization_access_organization_id"),
        table_name="desktop_organization_access",
        schema="deskconn",
    )
    op.drop_index(
        op.f("ix_deskconn_desktop_organization_access_desktop_id"),
        table_name="desktop_organization_access",
        schema="deskconn",
    )
    op.drop_table("desktop_organization_access", schema="deskconn")
    op.drop_index(op.f("ix_deskconn_desktop_invites_inviter_id"), table_name="desktop_invites", schema="deskconn")
    op.drop_index(op.f("ix_deskconn_desktop_invites_invitee_user_id"), table_name="desktop_invites", schema="deskconn")
    op.drop_index(
        op.f("ix_deskconn_desktop_invites_invitee_organization_id"), table_name="desktop_invites", schema="deskconn"
    )
    op.drop_index(op.f("ix_deskconn_desktop_invites_desktop_id"), table_name="desktop_invites", schema="deskconn")
    op.drop_table("desktop_invites", schema="deskconn")
    # ### end Alembic commands ###
