ERROR_USER_EXISTS = "io.xconn.error.user_exists"
ERROR_USER_NOT_FOUND = "io.xconn.error.user_not_found"
ERROR_DEVICE_EXISTS = "io.xconn.error.device_exists"
ERROR_DEVICE_NOT_FOUND = "io.xconn.error.device_not_found"
ERROR_USER_OTP_INVALID = "io.xconn.error.user_otp_invalid"
ERROR_USER_ALREADY_VERIFIED = "io.xconn.error.user_already_verified"
ERROR_USER_NOT_VERIFIED = "io.xconn.error.user_not_verified"
